### ISSUE TITLE
Teilen-Bild für 2018 anpassen

### ISSUE THREAD

**Issue by afoeder** [edsh/oldtimer-trifft-flugplatz-www#1]
Hey @sabrinatxt, kannst Du https://github.com/edsh/oldtimer-trifft-flugplatz-www/blob/master/docs/img/oldtimer-trifft-flugplatz-share-it.jpg bitte für 2018 anpassen? 😚

**Comment by sabrinatxt** [comment]
![share_it_2018](https://user-images.githubusercontent.com/37343005/42409153-651c7b2a-81d6-11e8-933d-8ad37661cac2.jpg)

Voilà :-)
